version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "webinars/Qdrant/gatling"
      - "webinars/Koyeb/gatling"
      - "webinars/Koyeb/.github/workflows"
      - "webinars/Docker/.github/workflows"
      - "webinars/Docker/gatling"
      - "articles/websocketguide/Gatling"
      - "articles/load-test-llm-sse"
      - "articles/gitlabintegration/Gatling/java"
      - "articles/githubintegration/Gatling/java"
      - "articles/datafaker/Gatling"
    groups:
      gatling:
        patterns:
          - "io.gatling*"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "github-actions"
    directories:
      - "webinars/Koyeb/.github/workflows"
      - "webinars/Docker/.github/workflows"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "npm"
    directories:
      - "meetup/AI_Developer_Meetup/gatling"
      - "articles/gitlabintegration/Gatling/javascript"
      - "articles/githubintegration/Gatling/javascript"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "thursday"
